import test from "node:test";import assert from "node:assert/strict";import{readFile}from"node:fs/promises";
const html=await readFile(new URL("../index.html",import.meta.url),"utf8"),app=await readFile(new URL("../app.js",import.meta.url),"utf8"),raw=await readFile(new URL("../data.js",import.meta.url),"utf8"),data=JSON.parse(raw.replace(/^window\.PRICING_DATA\s*=\s*/,"").replace(/;\s*$/,""));
test("source coverage and grain are preserved",()=>{assert.equal(data.summary.rows,10324);assert.equal(data.summary.arv_rows,8550);assert.equal(data.summary.countries,43);assert.deepEqual(data.summary.years,[2006,2015]);assert.equal(data.source.grain,"One shipment line item")});
test("eligible record calculations reconcile",()=>{assert.equal(data.records.length,6162);const freight=data.records.reduce((s,r)=>s+r.freight_cost,0);assert.ok(freight>0);assert.ok(data.records.every(r=>r.weight_kg>0&&r.freight_cost>0&&r.item_value>0));assert.ok(data.records.every(r=>Math.abs(r.freight_per_kg-r.freight_cost/r.weight_kg)<.01))});
test("model evaluation is bounded and documented",()=>{assert.ok(data.model.training_rows>0&&data.model.test_rows>0);assert.ok(data.model.r2_log<1&&data.model.r2_log>0);assert.ok(data.model.mae_usd>0);assert.match(data.model.method,/Chronological 80\/20/) });
test("all five product workflows exist",()=>{for(const id of["network-view","quote-view","drivers-view","exceptions-view","audit-view"])assert.match(html,new RegExp(`id=["']${id}["']`));for(const fn of["renderQuote","renderExceptions","drawImportance","evidenceAnswer"])assert.match(app,new RegExp(`function ${fn}\\b`))});
test("DOM ids are unique and literal selectors resolve",()=>{const ids=[...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);const set=new Set(ids),queried=[...app.matchAll(/\$\(["']#([A-Za-z0-9_-]+)["']\)/g)].map(m=>m[1]);assert.deepEqual([...new Set(queried)].filter(id=>!set.has(id)),[])});
test("quote benchmarks expose sample and interquartile range",()=>{assert.ok(data.benchmarks.length>20);assert.ok(data.benchmarks.every(r=>r.shipments>=5));assert.ok(data.benchmarks.every(r=>r.p25_freight_per_kg<=r.median_freight_per_kg&&r.median_freight_per_kg<=r.p75_freight_per_kg))});
test("quality caveats expose material missingness",()=>{const joined=data.quality.map(q=>q.evidence).join(" ");assert.match(joined,/missing freight cost/);assert.match(joined,/missing shipment weight/)});
