(function(){
"use strict";
const D=window.PRICING_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={view:"network",product:"All",mode:"All",country:"All",exception:"All",limit:25,quoteCounter:1};
const viewMeta={network:["ROUTE BOARD / HISTORICAL SNAPSHOT","Network pulse"],quote:["EMPIRICAL BENCHMARKING","Quote lab"],drivers:["EXPLAINABLE FREIGHT MODEL","Cost drivers"],exceptions:["ROBUST PEER DEVIATION","Exception manifest"],audit:["DATA QUALITY & GOVERNANCE","Trust center"]};
const dictionary=[
  ["Procurement value","Sum of line-item value; this is not company revenue."],
  ["Captured freight spend","Sum of positive freight cost among rows where freight was recorded."],
  ["Freight / kg","Freight cost divided by positive shipment weight; missing or zero weight is excluded."],
  ["Freight / item value","Freight cost divided by positive line-item value, expressed as a percentage."],
  ["On-time rate","Delivered-to-client date on or before scheduled delivery date."],
  ["Peer price index","Shipment freight/kg divided by median freight/kg for the same mode and weight band."],
  ["Quote range","Country-mode historical 25th to 75th percentile freight/kg multiplied by proposed weight."],
  ["Model R² (log)","Explained variance on log freight cost using the chronological holdout set."],
];
const money=(v,compact=true)=>{v=Number(v)||0;if(compact&&Math.abs(v)>=1e9)return`$${(v/1e9).toFixed(2)}B`;if(compact&&Math.abs(v)>=1e6)return`$${(v/1e6).toFixed(2)}M`;if(compact&&Math.abs(v)>=1e3)return`$${(v/1e3).toFixed(1)}K`;return`$${Math.round(v).toLocaleString()}`};
const num=v=>(Number(v)||0).toLocaleString();const pct=v=>`${(100*(Number(v)||0)).toFixed(1)}%`;const pctRaw=v=>`${(Number(v)||0).toFixed(1)}%`;const median=a=>{const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const esc=x=>String(x??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function scope(){return D.records.filter(r=>(state.product==="All"||r.product===state.product)&&(state.mode==="All"||r.mode===state.mode)&&(state.country==="All"||r.country===state.country))}
function summarize(rows){const value=rows.reduce((s,r)=>s+r.item_value,0),freight=rows.reduce((s,r)=>s+r.freight_cost,0);return{shipments:rows.length,value,freight,medianRate:median(rows.map(r=>r.freight_per_kg)),medianRatio:median(rows.map(r=>r.freight_pct_value)),onTime:rows.length?rows.filter(r=>r.on_time).length/rows.length:0,countries:new Set(rows.map(r=>r.country)).size}}
function group(rows,key){const m={};rows.forEach(r=>(m[r[key]]??=[]).push(r));return Object.entries(m).map(([name,items])=>({name,items,...summarize(items)}))}
function toast(message){const e=document.createElement("div");e.className="toast";e.textContent=message;$("#toast-zone").append(e);setTimeout(()=>e.remove(),2500)}
function download(name,text,type="text/plain"){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);toast(`${name} downloaded`)}
function csv(rows){if(!rows.length)return"";const h=Object.keys(rows[0]);return`${h.join(",")}\n${rows.map(r=>h.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(",")).join("\n")}`}
function showView(view){state.view=view;$$('.view').forEach(e=>e.classList.toggle('active',e.id===`${view}-view`));$$('.rail-link').forEach(e=>e.classList.toggle('active',e.dataset.view===view));$("#view-kicker").textContent=viewMeta[view][0];$("#view-title").textContent=viewMeta[view][1];window.scrollTo({top:0,behavior:"smooth"});requestAnimationFrame(drawCharts)}
function initFilters(){const vals=k=>[...new Set(D.records.map(r=>r[k]))].sort();for(const [id,key] of [["product-filter","product"],["mode-filter","mode"],["country-filter","country"]]){$(id.startsWith('#')?id:`#${id}`).insertAdjacentHTML("beforeend",vals(key).map(v=>`<option>${esc(v)}</option>`).join(""))}const countries=[...new Set(D.benchmarks.map(r=>r.country))].sort();$("#scenario-country").innerHTML=countries.map((v,i)=>`<option ${v==="Nigeria"||(!countries.includes("Nigeria")&&i===0)?"selected":""}>${esc(v)}</option>`).join("");updateScenarioModes()}
function renderMetrics(){const s=summarize(scope());$("#scope-count").textContent=num(s.shipments);const cards=[["ELIGIBLE SHIPMENT LINES",num(s.shipments),`${s.countries} destination countries`],["PROCUREMENT VALUE",money(s.value),"Sum of item value"],["CAPTURED FREIGHT",money(s.freight),"Positive recorded freight"],["MEDIAN FREIGHT / KG",money(s.medianRate,false),"Eligible weight + freight rows"],["MEDIAN FREIGHT / VALUE",pctRaw(s.medianRatio),"Cost-to-serve pressure"],["ON-TIME RATE",pct(s.onTime),"Delivered on/before schedule"]];$("#metric-grid").innerHTML=cards.map(([l,v,n])=>`<article class="metric-card"><span>${l}</span><strong>${v}</strong><small>${n}</small></article>`).join("")}
function renderDispatch(){const rows=scope(),s=summarize(rows),countries=group(rows,"country").filter(x=>x.shipments>=5).sort((a,b)=>b.medianRatio-a.medianRatio),modes=group(rows,"mode").sort((a,b)=>b.medianRate-a.medianRate),pressure=countries[0],mode=modes[0];let head="The active manifest has a measurable cost-to-serve concentration.";let copy=pressure?`${pressure.name} has the highest median freight-to-item-value ratio among scoped countries with at least five eligible lines. ${mode?.name||"The leading mode"} carries the highest median freight-per-kilogram in this scope.`:"Broaden the filters to create a reliable peer comparison.";$("#dispatch-headline").textContent=head;$("#dispatch-copy").textContent=copy;$("#dispatch-evidence").innerHTML=`<div><span>FREIGHT PRESSURE</span><strong>${pressure?`${pressure.name} · ${pctRaw(pressure.medianRatio)}`:"Insufficient sample"}</strong></div><div><span>MODE SIGNAL</span><strong>${mode?`${mode.name} · ${money(mode.medianRate,false)}/kg`:"Insufficient sample"}</strong></div><div><span>EVIDENCE SCOPE</span><strong>${num(s.shipments)} eligible lines · supplied CSV</strong></div>`}
function renderCountries(){const rows=group(scope(),"country").filter(r=>r.shipments>=5).sort((a,b)=>b.freight-a.freight).slice(0,6),max=Math.max(...rows.map(r=>r.freight),1);$("#country-ranking").innerHTML=rows.map((r,i)=>`<div class="rank-row"><b>${String(i+1).padStart(2,"0")}</b><span>${esc(r.name)}</span><div class="rank-track"><i style="width:${100*r.freight/max}%"></i></div><strong>${money(r.freight)}</strong></div>`).join("")||`<div class="rank-row">No eligible lanes in this scope.</div>`}
function renderModes(){const rows=group(scope(),"mode").sort((a,b)=>b.shipments-a.shipments);$("#mode-cards").innerHTML=rows.map(r=>`<div class="mode-card"><span>${num(r.shipments)} LINES</span><h3>${esc(r.name)}</h3><div><small>MEDIAN / KG</small><strong>${money(r.medianRate,false)}</strong></div><div><small>ON TIME</small><strong>${pct(r.onTime)}</strong></div></div>`).join("")}
function renderModel(){const m=D.model;$("#model-strip").innerHTML=[["HOLDOUT R² · LOG",m.r2_log.toFixed(3),"Primary generalization score"],["HOLDOUT R² · USD",m.r2_dollars.toFixed(3),"Dollar-scale variance explained"],["MEAN ABSOLUTE ERROR",money(m.mae_usd,false),"Chronological holdout"],["TRAIN / TEST",`${num(m.training_rows)} / ${num(m.test_rows)}`,"Complete eligible lines"]].map(([l,v,n])=>`<article class="model-card"><span>${l}</span><strong>${v}</strong><small>${n}</small></article>`).join("");$("#model-method").textContent=m.method}
function exceptionRows(){let rows=D.anomalies.filter(r=>(state.product==="All"||r.product===state.product)&&(state.mode==="All"||r.mode===state.mode)&&(state.country==="All"||r.country===state.country));const q=$("#exception-search").value.trim().toLowerCase();if(q)rows=rows.filter(r=>`${r.country} ${r.mode} ${r.vendor} ${r.molecule}`.toLowerCase().includes(q));if(state.exception==="Extreme")rows=rows.filter(r=>r.price_index>=3);if(state.exception==="Review")rows=rows.filter(r=>r.price_index<3);return rows}
function renderExceptions(){const all=D.anomalies.filter(r=>(state.product==="All"||r.product===state.product)&&(state.mode==="All"||r.mode===state.mode)&&(state.country==="All"||r.country===state.country)),extreme=all.filter(r=>r.price_index>=3).length;$("#exception-summary").innerHTML=[["PRIORITY QUEUE",all.length,"Top robust deviations retained"],["EXTREME INDEX",extreme,"Peer price index ≥ 3×"],["FREIGHT AT REVIEW",money(all.reduce((s,r)=>s+r.freight_cost,0)),"Captured freight in queue"],["COUNTRIES AFFECTED",new Set(all.map(r=>r.country)).size,"Destination coverage"]].map(([l,v,n])=>`<article class="exception-card"><span>${l}</span><strong>${v}</strong><small>${n}</small></article>`).join("");const rows=exceptionRows();$("#exception-count").textContent=`${rows.length} FLAGS`;$("#exception-body").innerHTML=rows.slice(0,state.limit).map(r=>`<tr><td><span class="flag ${r.price_index>=3?"extreme":"review"}">${r.price_index>=3?"EXTREME":"REVIEW"}</span></td><td><strong>#${r.id}</strong><br><small>${r.year}</small></td><td><strong>${esc(r.country)}</strong><br><small>${esc(r.product)} · ${esc(r.classification)}</small></td><td>${esc(r.mode)}</td><td>${num(Math.round(r.weight_kg))} kg</td><td><strong>${money(r.freight_cost,false)}</strong><br><small>${money(r.freight_per_kg,false)}/kg</small></td><td>${r.price_index.toFixed(2)}×</td><td>${esc(r.reason)}</td></tr>`).join("")||`<tr><td colspan="8">No exceptions match the active manifest.</td></tr>`;$("#table-status").textContent=`SHOWING ${Math.min(state.limit,rows.length)} OF ${rows.length}`;$("#show-more").style.visibility=state.limit<rows.length?"visible":"hidden"}
function renderQuality(){$("#quality-grid").innerHTML=D.quality.map(q=>`<article class="quality-card ${q.status}"><span>${esc(q.check)} · ${esc(q.status.toUpperCase())}</span><strong>${esc(q.evidence)}</strong><small>IMPACT: ${esc(q.severity)}</small></article>`).join("");$("#metric-dictionary").innerHTML=`<div class="dictionary-list">${dictionary.map(([m,d])=>`<div class="dictionary-item"><strong>${m}</strong><p>${d}</p></div>`).join("")}</div>`}
function updateScenarioModes(){const country=$("#scenario-country").value,modes=D.benchmarks.filter(r=>r.country===country).map(r=>r["shipment mode"]),current=$("#scenario-mode").value;$("#scenario-mode").innerHTML=modes.map(v=>`<option ${v===current?"selected":""}>${esc(v)}</option>`).join("");renderQuote()}
function renderQuote(){const country=$("#scenario-country").value,mode=$("#scenario-mode").value,weight=Number($("#scenario-weight").value),value=Number($("#scenario-value").value),quantity=Number($("#scenario-quantity").value);$("#weight-output").textContent=`${num(weight)} KG`;$("#value-output").textContent=money(value,false);$("#quantity-output").textContent=num(quantity);const peer=D.benchmarks.find(r=>r.country===country&&r["shipment mode"]===mode);$("#ticket-country").textContent=country.toUpperCase();$("#quote-id").textContent=`LQ-${String(state.quoteCounter).padStart(4,"0")}`;if(!peer){for(const id of ["expected-cost","expected-range","peer-rate","quote-ratio","peer-sample","quote-confidence"])$("#"+id).textContent="N/A";$("#quote-ai-headline").textContent="No reliable peer lane.";$("#quote-ai-copy").textContent="Choose another mode-country combination.";return}const expected=peer.median_freight_per_kg*weight,low=peer.p25_freight_per_kg*weight,high=peer.p75_freight_per_kg*weight,ratio=100*expected/value,confidence=peer.shipments>=50?"HIGH":peer.shipments>=20?"MEDIUM":"DIRECTIONAL";$("#expected-cost").textContent=money(expected,false);$("#expected-range").textContent=`IQR ${money(low,false)} — ${money(high,false)}`;$("#peer-rate").textContent=`${money(peer.median_freight_per_kg,false)}`;$("#quote-ratio").textContent=pctRaw(ratio);$("#peer-sample").textContent=`n=${peer.shipments}`;$("#quote-confidence").textContent=confidence;const alternatives=D.benchmarks.filter(r=>r.country===country&&r["shipment mode"]!==mode&&r.shipments>=5).map(r=>({...r,estimate:r.median_freight_per_kg*weight})).sort((a,b)=>a.estimate-b.estimate).slice(0,2),best=alternatives[0],delta=best?expected-best.estimate:0;$("#quote-ai-headline").textContent=ratio>20?"Cost-to-serve pressure is elevated.":"The peer quote stays inside a manageable value ratio.";$("#quote-ai-copy").textContent=`The ${mode} peer median implies ${money(expected,false)} of freight for ${num(weight)} kg, equal to ${pctRaw(ratio)} of item value. ${ratio>20?"Validate consolidation, mode, and incoterm assumptions before approval.":"Confirm service requirements and lane availability before treating the range as a quote."}`;$("#quote-alternatives").innerHTML=best?alternatives.map(a=>`<div class="alternative"><span>HISTORICAL MODE ALTERNATIVE</span><strong>${esc(a["shipment mode"])} · ${money(a.estimate,false)}</strong><small>${delta>0?`${money(expected-a.estimate,false)} below selected median`:"Peer comparison only"}</small></div>`).join(""):`<div class="alternative"><span>NO QUALIFIED ALTERNATIVE</span><strong>Validate with procurement</strong></div>`;$("#quote-citation").textContent=`[peer lane | ${mode} × ${country} | n=${peer.shipments} | supplied CSV]`}
function setupCanvas(canvas,height){if(!canvas||canvas.offsetParent===null)return null;const r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1;if(!r.width)return null;canvas.width=r.width*d;canvas.height=height*d;canvas.style.height=height+"px";const c=canvas.getContext("2d");c.setTransform(d,0,0,d,0,0);return{c,w:r.width,h:height}}
function drawAnnual(){const x=setupCanvas($("#annual-chart"),315);if(!x)return;const{c,w,h}=x,rows=group(scope(),"year").sort((a,b)=>Number(a.name)-Number(b.name)),pad={l:58,r:45,t:28,b:36},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b,maxF=Math.max(...rows.map(r=>r.freight),1)*1.12,maxN=Math.max(...rows.map(r=>r.shipments),1)*1.12;c.font='8px "Courier New"';c.strokeStyle="#d8d1c5";c.fillStyle="#736f68";for(let i=0;i<5;i++){let y=pad.t+i*ph/4;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillText(money(maxF*(1-i/4)),3,y+3)}rows.forEach((r,i)=>{const x0=pad.l+(i+.5)*pw/Math.max(rows.length,1),bw=Math.min(30,pw/rows.length*.5),bh=ph*r.freight/maxF;c.fillStyle="#2142ff";c.fillRect(x0-bw/2,pad.t+ph-bh,bw,bh);c.fillStyle="#736f68";c.fillText(r.name,x0-13,h-10)});c.strokeStyle="#ff6b35";c.lineWidth=3;c.beginPath();rows.forEach((r,i)=>{const x0=pad.l+(i+.5)*pw/rows.length,y=pad.t+ph*(1-r.shipments/maxN);i?c.lineTo(x0,y):c.moveTo(x0,y)});c.stroke();$("#annual-caption").textContent=`${rows.length} annual points · bars use freight USD; line uses shipment count`}
function drawImportance(){const x=setupCanvas($("#importance-chart"),330);if(!x)return;const{c,w,h}=x,rows=D.model.drivers.slice(0,8).reverse(),left=150,right=35,top=22,rh=(h-42)/rows.length,max=Math.max(...rows.map(r=>r.importance));c.font='8px "Courier New"';rows.forEach((r,i)=>{const y=top+i*rh;c.fillStyle="#736f68";c.fillText(r.feature.slice(0,24),9,y+13);c.fillStyle="#ebe5da";c.fillRect(left,y,w-left-right,14);c.fillStyle=i===rows.length-1?"#ff6b35":"#2142ff";c.fillRect(left,y,(w-left-right)*r.importance/max,14);c.fillStyle="#101522";c.fillText(`${(100*r.importance).toFixed(1)}%`,w-right+3,y+12)})}
function drawRelationship(){const x=setupCanvas($("#relationship-chart"),330);if(!x)return;const{c,w,h}=x,rows=scope().filter((_,i)=>i%Math.max(1,Math.floor(scope().length/650))===0).slice(0,650),pad=38;const lx=r=>Math.log10(Math.max(r.weight_kg,1)),ly=r=>Math.log10(Math.max(r.freight_cost,1)),xs=rows.map(lx),ys=rows.map(ly),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);c.strokeStyle="#d8d1c5";for(let i=0;i<5;i++){const q=pad+i*(w-2*pad)/4;c.beginPath();c.moveTo(q,pad);c.lineTo(q,h-pad);c.stroke()}rows.forEach(r=>{const px=pad+(lx(r)-xmin)/(xmax-xmin||1)*(w-2*pad),py=h-pad-(ly(r)-ymin)/(ymax-ymin||1)*(h-2*pad);c.fillStyle=r.mode==="Air"?"rgba(33,66,255,.45)":r.mode==="Truck"?"rgba(255,107,53,.5)":"rgba(8,123,89,.42)";c.beginPath();c.arc(px,py,2.2,0,Math.PI*2);c.fill()});c.fillStyle="#736f68";c.font='8px "Courier New"';c.fillText("LOW WEIGHT",pad,h-9);c.fillText("HIGH WEIGHT",w-pad-58,h-9);c.save();c.translate(10,h/2+35);c.rotate(-Math.PI/2);c.fillText("FREIGHT COST · LOG",0,0);c.restore();$("#relationship-caption").textContent=`${rows.length} sampled eligible lines · point tone indicates mode`}
function drawCharts(){drawAnnual();drawImportance();drawRelationship()}
function evidenceAnswer(question){const rows=scope(),s=summarize(rows),countries=group(rows,"country").filter(r=>r.shipments>=5).sort((a,b)=>b.medianRatio-a.medianRatio),modes=group(rows,"mode").sort((a,b)=>b.medianRate-a.medianRate),q=question.toLowerCase(),items=[];if(q.includes("mode")){items.push([`${modes[0]?.name||"No mode"} has the highest scoped median freight/kg at ${money(modes[0]?.medianRate||0,false)}.`,`[mode benchmark | ${modes[0]?.name||"n/a"} | n=${modes[0]?.shipments||0} | supplied CSV]`])}else if(q.includes("investigate")||q.includes("exception")){const e=D.anomalies.filter(r=>(state.country==="All"||r.country===state.country))[0];items.push([e?`Line ${e.id} is a priority exception at ${e.price_index.toFixed(2)}× its peer freight/kg benchmark.`:"No priority exception is available in this scope.",e?`[peer exception | line ${e.id} | ${e.mode} × ${e.weight_band} | supplied CSV]`:"[active manifest | no record]"])}else{items.push([`${countries[0]?.name||"No country"} has the highest median freight-to-value pressure at ${pctRaw(countries[0]?.medianRatio||0)} among qualified scoped countries.`,`[country benchmark | ${countries[0]?.name||"n/a"} | n=${countries[0]?.shipments||0} | supplied CSV]`]);items.push([`The active manifest contains ${num(s.shipments)} eligible lines and ${money(s.freight)} in captured freight.`,`[active manifest | eligible weight + freight | supplied CSV]`])}return items}
function askAI(question){$("#ai-log").insertAdjacentHTML("beforeend",`<div class="user-bubble"><p>${esc(question)}</p></div>`);const findings=evidenceAnswer(question);$("#ai-log").insertAdjacentHTML("beforeend",`<div class="ai-bubble"><b>LANDED AI / VERIFIED</b>${findings.map(([f,c])=>`<div class="finding"><p>${esc(f)}</p><code>${esc(c)}</code></div>`).join("")}<div class="finding"><p><strong>Hypothesis to validate:</strong> lane availability, consolidation, incoterm, and urgency may explain the observed pattern; the supplied evidence does not establish causality.</p></div></div>`);$("#ai-log").lastElementChild.scrollIntoView({behavior:"smooth"})}
function openAI(){$("#ai-drawer").classList.add("open");$("#backdrop").classList.add("open");$("#ai-drawer").setAttribute("aria-hidden","false");$("#ai-scope").textContent=`${num(scope().length)} eligible lines · ${state.product}/${state.mode}/${state.country}`}
function closeAI(){$("#ai-drawer").classList.remove("open");$("#backdrop").classList.remove("open");$("#ai-drawer").setAttribute("aria-hidden","true")}
function refresh(){renderMetrics();renderDispatch();renderCountries();renderModes();renderModel();renderExceptions();renderQuality();requestAnimationFrame(drawCharts)}
function wire(){$$('.rail-link').forEach(e=>e.addEventListener('click',()=>showView(e.dataset.view)));$$('[data-jump]').forEach(e=>e.addEventListener('click',()=>showView(e.dataset.jump)));for(const [id,key] of [["product-filter","product"],["mode-filter","mode"],["country-filter","country"]])$("#"+id).addEventListener("change",e=>{state[key]=e.target.value;state.limit=25;refresh()});$("#reset-scope").addEventListener("click",()=>{state.product=state.mode=state.country="All";for(const id of ["product-filter","mode-filter","country-filter"])$("#"+id).value="All";refresh()});$("#dispatch-to-quote").addEventListener("click",()=>showView("quote"));$("#quote-form").addEventListener("submit",e=>{e.preventDefault();state.quoteCounter++;renderQuote();toast("Peer quote recalculated")});$("#scenario-country").addEventListener("change",updateScenarioModes);$("#scenario-mode").addEventListener("change",renderQuote);for(const id of ["scenario-weight","scenario-value","scenario-quantity"])$("#"+id).addEventListener("input",renderQuote);$$('[data-exception]').forEach(e=>e.addEventListener('click',()=>{$$('[data-exception]').forEach(x=>x.classList.remove('active'));e.classList.add('active');state.exception=e.dataset.exception;state.limit=25;renderExceptions()}));$("#exception-search").addEventListener("input",()=>{state.limit=25;renderExceptions()});$("#show-more").addEventListener("click",()=>{state.limit+=25;renderExceptions()});$("#download-exceptions").addEventListener("click",()=>download("arv_pricing_exceptions.csv",csv(exceptionRows()),"text/csv"));$("#export-view").addEventListener("click",()=>download(`landed-${state.view}-snapshot.json`,JSON.stringify({scope:{product:state.product,mode:state.mode,country:state.country},metrics:summarize(scope()),source:D.source},null,2),"application/json"));$("#open-ai").addEventListener("click",openAI);$("#close-ai").addEventListener("click",closeAI);$("#backdrop").addEventListener("click",closeAI);$("#ai-form").addEventListener("submit",e=>{e.preventDefault();const q=$("#ai-input").value.trim();if(q){askAI(q);$("#ai-input").value=""}});$$('.prompt-row button').forEach(e=>e.addEventListener('click',()=>askAI(e.textContent)));window.addEventListener("resize",drawCharts)}
initFilters();wire();refresh();renderQuote();
})();
